### ISSUE TITLE
Add Leon

### ISSUE THREAD

**Issue by amkrajewski** [PhasesResearchLab/SoftwareProjects#6]
Hi @Leon-526, Please add yourself to the Active Members list. Consult @lukeamyers if you need assistance.

**Comment by Leon-526** [comment]
Task completed

**Comment by amkrajewski** [comment]
@Leon-526 Great! I will now close the Issue. BTW, I would recommend that you update your ORCID profile with education and work experience.

**Comment by Leon-526** [comment]
Thank you, I will do that.
